// config.h
#ifndef CONFIG_H
#define CONFIG_H

#define FIREBASE_HOST1 "HOST1_URL"
#define FIREBASE_AUTH1 "HOST1_AUTH"
#define FIREBASE_HOST2 "HOST2_URL"
#define FIREBASE_AUTH2 "HOST2_AUTH"
#define WIFI_SSID "WIFI_SSID"
#define WIFI_PASSWORD "WIFI_PASSWORD"

#endif